In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
def compare_anomaly_models(*model_dfs, id_column='TestKey'):
    df_combined = pd.DataFrame({id_column: model_dfs[0][0][id_column]})
    
    # Voeg resultaten van elk model toe
    number_of_anomalies = 0
    model_names = []
    for df, model_name in model_dfs:
        number_of_anomalies +=1 
        model_names.append(model_name)
        df_combined = df_combined.merge(
            df[[id_column, 'is_anomaly']],
            on=id_column,
            suffixes=('', f'_{model_name}')
        )
        df_combined = df_combined.rename(columns={'is_anomaly': f'{model_name}_anomaly'})
    
    anomaly_columns = [col for col in df_combined.columns if col.endswith('_anomaly')]
    df_combined['anomaly_count'] = df_combined[anomaly_columns].sum(axis=1)

    df_combined['anomaly_score'] = df_combined['anomaly_count'] / number_of_anomalies 
    
    return df_combined

## Test 
### import csv's

In [ ]:
df_copod = pd.read_csv('./csv/copod.csv')
df_ecod = pd.read_csv('./csv/ecod.csv')
df_i_forest = pd.read_csv('./csv/i_forest.csv')
df_lof = pd.read_csv('./csv/lof.csv')
df_abod = pd.read_csv('./csv/abod.csv')
df_neighbours = pd.read_csv('./csv/neighbours.csv')

### Compare and anomaly score

In [ ]:
df_compare = compare_anomaly_models(
    (df_copod, 'copod'), 
    (df_ecod, 'ecod'), 
    (df_i_forest, 'i_forest'),
    (df_lof, 'lof'),
    (df_abod, 'abod'),
    (df_neighbours, 'neighbours'),
    id_column='TestKey'
)
df_compare.head()

,TestKey,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
0,251025,1,1,0,0,0,2,0.4
1,251170,1,1,1,0,1,4,0.8
2,251171,1,1,0,0,0,2,0.4
3,251172,1,1,0,0,1,3,0.6
4,251173,1,1,0,0,0,2,0.4

In [15]:
df_compare.to_csv('./csv/compare.csv', index=False)

In [16]:
df_test_anomalies = df_compare
df_test_anomalies

,TestKey,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
0,251025,1,1,0,0,0,2,0.4
1,251170,1,1,1,0,1,4,0.8
2,251171,1,1,0,0,0,2,0.4
3,251172,1,1,0,0,1,3,0.6
4,251173,1,1,0,0,0,2,0.4
...,...,...,...,...,...,...,...,...
249769,501604,1,1,0,0,0,2,0.4
249770,501605,1,1,1,0,0,3,0.6
249771,501606,0,1,0,0,0,1,0.2
249772,501607,0,1,0,0,0,1,0.2
249773,501608,1,1,0,0,1,3,0.6

### Store in DimTestAnomalies

In [17]:
df_test_anomalies.set_index("TestKey", inplace=True)
df_test_anomalies.to_csv("../../decoded_data/MDQ/DimTestAnomalies.csv")
df_test_anomalies.head()

,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
TestKey,,,,,,,
251025,1,1,0,0,0,2,0.4
251170,1,1,1,0,1,4,0.8
251171,1,1,0,0,0,2,0.4
251172,1,1,0,0,1,3,0.6
251173,1,1,0,0,0,2,0.4