In [1]:
import pyodbc
import pandas as pd

In [2]:
df_test = pd.read_csv('../../../decoded_data/MDQ/FactTest.csv')
df_question = pd.read_csv('../../../decoded_data/MDQ/FactQuestionMDQ.csv')

In [3]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257592 entries, 0 to 257591
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Test             257592 non-null  object
 1   CandidateKey     257592 non-null  int64
 2   CreatedDateKey   249774 non-null  float64
 3   ModifiedDateKey  249775 non-null  float64
 4   VersionNumber    256864 non-null  object
 5   TestKey          257592 non-null  int64
dtypes: float64(2), int64(2), object(2)
memory usage: 11.8+ MB

In [4]:
df_question.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3348611 entries, 0 to 3348610
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   itemId       int64
 1   FirstVal     int64
 2   SecondVal    int64
 3   ThirdVal     int64
 4   FourthVal    int64
 5   FifthVal     int64
 6   SixthVal     int64
 7   Test         object
 8   QuestionKey  int64
 9   TestKey      int64
dtypes: int64(9), object(1)
memory usage: 255.5+ MB

In [5]:
df_test.drop(columns=['VersionNumber', 'Test', 'ModifiedDateKey'], inplace=True)
df_test.head()

   CandidateKey  CreatedDateKey  TestKey
0       1087731             NaN   255111
1       1265541             NaN   255112
2       1267201             NaN   255113
3       1270201             NaN   255114
4       1279241             NaN   255115

In [6]:
df_question.drop(columns=['Test'], inplace=True)
df_question.head()

,itemId,FirstVal,SecondVal,ThirdVal,FourthVal,FifthVal,SixthVal,QuestionKey,TestKey
0,2,4,0,0,6,0,0,1,255111
1,3,4,0,0,6,0,0,2,255111
2,3,0,1,0,6,0,0,3,255111
3,1,0,1,0,6,0,0,4,255111
4,1,4,1,0,2,0,0,5,255111

In [7]:
df = df_question.merge(df_test, on='TestKey')
df.head()

,itemId,FirstVal,SecondVal,ThirdVal,FourthVal,FifthVal,SixthVal,QuestionKey,TestKey,CandidateKey,CreatedDateKey
0,2,4,0,0,6,0,0,1,255111,1087731,NaN
1,3,4,0,0,6,0,0,2,255111,1087731,NaN
2,3,0,1,0,6,0,0,3,255111,1087731,NaN
3,1,0,1,0,6,0,0,4,255111,1087731,NaN
4,1,4,1,0,2,0,0,5,255111,1087731,NaN

### Date

In [8]:
df["CreatedDateKey"] = pd.to_datetime(df.CreatedDateKey, format="%Y%m%d")
df.head()

,itemId,FirstVal,SecondVal,ThirdVal,FourthVal,FifthVal,SixthVal,QuestionKey,TestKey,CandidateKey,CreatedDateKey
0,2,4,0,0,6,0,0,1,255111,1087731,NaT
1,3,4,0,0,6,0,0,2,255111,1087731,NaT
2,3,0,1,0,6,0,0,3,255111,1087731,NaT
3,1,0,1,0,6,0,0,4,255111,1087731,NaT
4,1,4,1,0,2,0,0,5,255111,1087731,NaT

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3348611 entries, 0 to 3348610
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   itemId          int64
 1   FirstVal        int64
 2   SecondVal       int64
 3   ThirdVal        int64
 4   FourthVal       int64
 5   FifthVal        int64
 6   SixthVal        int64
 7   QuestionKey     int64
 8   TestKey         int64
 9   CandidateKey    int64
 10  CreatedDateKey  datetime64[ns]
dtypes: datetime64[ns](1), int64(10)
memory usage: 281.0 MB

In [10]:
df['Year'] = pd.DatetimeIndex(df['CreatedDateKey']).year
df['Month'] = pd.DatetimeIndex(df['CreatedDateKey']).month
df['Day'] = pd.DatetimeIndex(df['CreatedDateKey']).dayofweek
df.drop(columns=['CreatedDateKey'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3348611 entries, 0 to 3348610
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   itemId        int64
 1   FirstVal      int64
 2   SecondVal     int64
 3   ThirdVal      int64
 4   FourthVal     int64
 5   FifthVal      int64
 6   SixthVal      int64
 7   QuestionKey   int64
 8   TestKey       int64
 9   CandidateKey  int64
 10  Year          float64
 11  Month         float64
 12  Day           float64
dtypes: float64(3), int64(10)
memory usage: 332.1 MB

In [11]:
df.head()

,itemId,FirstVal,SecondVal,ThirdVal,FourthVal,FifthVal,SixthVal,QuestionKey,TestKey,CandidateKey,Year,Month,Day
0,2,4,0,0,6,0,0,1,255111,1087731,NaN,NaN,NaN
1,3,4,0,0,6,0,0,2,255111,1087731,NaN,NaN,NaN
2,3,0,1,0,6,0,0,3,255111,1087731,NaN,NaN,NaN
3,1,0,1,0,6,0,0,4,255111,1087731,NaN,NaN,NaN
4,1,4,1,0,2,0,0,5,255111,1087731,NaN,NaN,NaN

## Cleaning

In [12]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3348611 entries, 0 to 3348610
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   itemId        int64
 1   FirstVal      int64
 2   SecondVal     int64
 3   ThirdVal      int64
 4   FourthVal     int64
 5   FifthVal      int64
 6   SixthVal      int64
 7   QuestionKey   int64
 8   TestKey       int64
 9   CandidateKey  int64
 10  Year          float64
 11  Month         float64
 12  Day           float64
dtypes: float64(3), int64(10)
memory usage: 332.1 MB

In [13]:
df.columns

Index(['itemId', 'FirstVal', 'SecondVal', 'ThirdVal', 'FourthVal', 'FifthVal',
       'SixthVal', 'QuestionKey', 'TestKey', 'CandidateKey', 'Year', 'Month',
       'Day'],
      dtype='object')

In [14]:
df.dropna(inplace=True)

### Samenvoegen

In [15]:
# Step 1: Melt the dataframe
df_melted = df.melt(id_vars=['TestKey', 'itemId', 'QuestionKey', 'CandidateKey'], 
                    value_vars=['FirstVal', 'SecondVal', 'ThirdVal', 'FourthVal', 'FifthVal', 'SixthVal'], 
                    var_name='answer_type', 
                    value_name='Answer')

# Step 2: Create a QuestionNr column
df_melted['QuestionNr'] = df_melted['answer_type'].map({
    'FirstVal': 1, 'SecondVal': 2, 'ThirdVal': 3,
    'FourthVal': 4, 'FifthVal': 5, 'SixthVal': 6
})

# Step 3: Drop the answer_type column
df_melted.drop(columns=["answer_type"], inplace=True)

# Step 4: Create the pivot table
df_pivot = df_melted.pivot_table(index=['TestKey', 'CandidateKey'], 
                                 columns=['itemId', 'QuestionNr'], 
                                 values='Answer', 
                                 aggfunc='first')

# Step 5: Rename the columns
df_pivot.columns = [f'Q{q}_A{a}' for q, a in df_pivot.columns]

# Step 6: Fill NaN values with 0.0
df_pivot.fillna(0.0, inplace=True)

# Optional: Reset the index if you want TestKey and CandidateKey as columns
df_pivot.reset_index(inplace=True)

In [16]:
df_pivot.head()

,TestKey,CandidateKey,Q0_A1,Q0_A2,Q0_A3,Q0_A4,Q0_A5,Q0_A6,Q1_A1,Q1_A2,...,Q2_A3,Q2_A4,Q2_A5,Q2_A6,Q3_A1,Q3_A2,Q3_A3,Q3_A4,Q3_A5,Q3_A6
0,262119,5640161,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0
1,262264,5021111,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,...,0.0,6.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0
2,262265,5033381,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,...,0.0,6.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0
3,262266,5104761,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,...,0.0,6.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0
4,262267,5034311,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,2.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0

In [17]:
df_pivot.columns

Index(['TestKey', 'CandidateKey', 'Q0_A1', 'Q0_A2', 'Q0_A3', 'Q0_A4', 'Q0_A5',
       'Q0_A6', 'Q1_A1', 'Q1_A2', 'Q1_A3', 'Q1_A4', 'Q1_A5', 'Q1_A6', 'Q2_A1',
       'Q2_A2', 'Q2_A3', 'Q2_A4', 'Q2_A5', 'Q2_A6', 'Q3_A1', 'Q3_A2', 'Q3_A3',
       'Q3_A4', 'Q3_A5', 'Q3_A6'],
      dtype='object')

In [18]:
df_pivot.to_csv('../csv/preprocessed_data.csv', index=False)