In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def compare_anomaly_models(*model_dfs, id_column='TestKey'):
    df_combined = pd.DataFrame({id_column: model_dfs[0][0][id_column]})
    
    # Voeg resultaten van elk model toe
    number_of_anomalies = 0
    model_names = []
    for df, model_name in model_dfs:
        number_of_anomalies +=1 
        model_names.append(model_name)
        df_combined = df_combined.merge(
            df[[id_column, 'is_anomaly']],
            on=id_column,
            suffixes=('', f'_{model_name}')
        )
        df_combined = df_combined.rename(columns={'is_anomaly': f'{model_name}_anomaly'})
    
    # Tel het aantal anomaliedetecties per datapunt
    anomaly_columns = [col for col in df_combined.columns if col.endswith('_anomaly')]
    df_combined['anomaly_count'] = df_combined[anomaly_columns].sum(axis=1)

    df_combined['anomaly_score'] = df_combined['anomaly_count'] / number_of_anomalies 
    
    return df_combined

## Test 
### import csv's

In [ ]:
df_copod = pd.read_csv('./csv/copod.csv')
df_ecod = pd.read_csv('./csv/ecod.csv')
df_i_forest = pd.read_csv('./csv/i_forest.csv')
df_lof = pd.read_csv('./csv/lof.csv')
df_abod = pd.read_csv('./csv/abod.csv')
df_neighbours = pd.read_csv('./csv/neighbours.csv')

### Compare and anomaly score

In [ ]:
df_compare = compare_anomaly_models(
    (df_copod, 'copod'), 
    (df_ecod, 'ecod'), 
    (df_i_forest, 'i_forest'),
    (df_lof, 'lof'),
    (df_abod, 'abod'),
    (df_neighbours, 'neighbours'),
    id_column='TestKey'
)
df_compare.head()

,TestKey,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
0,172548,0,0,0,0,0,0,0.0
1,172549,0,0,0,0,0,0,0.0
2,172550,0,0,0,0,0,0,0.0
3,172551,0,0,0,0,0,0,0.0
4,172552,0,0,0,0,0,0,0.0

In [5]:
df_compare.to_csv('./csv/compare.csv', index=False)

In [6]:
df_test_anomalies = df_compare
df_test_anomalies

,TestKey,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
0,172548,0,0,0,0,0,0,0.0
1,172549,0,0,0,0,0,0,0.0
2,172550,0,0,0,0,0,0,0.0
3,172551,0,0,0,0,0,0,0.0
4,172552,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...
21189,243998,0,0,0,0,0,0,0.0
21190,244004,0,0,0,0,0,0,0.0
21191,244007,0,0,0,0,0,0,0.0
21192,244008,0,0,0,0,0,0,0.0
21193,244010,0,0,0,0,0,0,0.0

### Store in DimTestAnomalies

In [7]:
df_test_anomalies.set_index("TestKey", inplace=True)
df_test_anomalies.to_csv("../../decoded_data/BA51/DimTestAnomalies.csv")
df_test_anomalies.head()

,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
TestKey,,,,,,,
172548,0,0,0,0,0,0,0.0
172549,0,0,0,0,0,0,0.0
172550,0,0,0,0,0,0,0.0
172551,0,0,0,0,0,0,0.0
172552,0,0,0,0,0,0,0.0

## QUESTION 
# import csvs

In [8]:
# df_question_same_ans = pd.read_csv('./csv/same_answers_question_checked.csv')
# df_question_time_spent = pd.read_csv('./csv/time_spent_question_checked.csv')


# same answer + time spent

In [9]:
# df_question_anomalies = df_question_time_spent.merge(df_question_same_ans)


# store in DimQuestionAnomalies

In [10]:
# df_question_anomalies.set_index("QuestionKey", inplace=True)
# df_question_anomalies.to_csv('../../decoded_data/SJT/DimQuestionAnomalies.csv')