imports

In [12]:
import pandas as pd
from dep2pyodbc import dep2connection

Connection to database

In [13]:
DATABASE = 'CRH'
DB_DWH = 'CRH_DWH'

channel_dwh = dep2connection(DATABASE, True)
channel_dwh_lisa = dep2connection(DB_DWH)
cursor_dwh_lisa = channel_dwh_lisa.cursor()

pyodbc using windows
DRIVER=ODBC Driver 17 for SQL Server;SERVER=MONAS_CUTIE;DATABASE=CRH;UID=MONAS_CUTIE\\monad;Trusted_Connection=yes
pyodbc using windows

Get data from candidate table in CRH en put it in a dataframe

In [14]:
df_candidate = pd.read_sql("SELECT * FROM Candidate", channel_dwh)

df_candidate.info()

C:\Users\monad\AppData\Local\Temp\ipykernel_22816\4104127695.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_candidate = pd.read_sql("SELECT * FROM Candidate", channel_dwh)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2292756 entries, 0 to 2292755
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   ID                 int64
 1   InstanceID         int64
 2   AssessmentGUID     object
 3   InstrumentClassID  int64
 4   LanguageGUID       object
 5   OrganizationGUID   object
 6   Gender             object
 7   GenderChoice       object
 8   Qualification      object
dtypes: int64(3), object(6)
memory usage: 157.4+ MB

Use only columns that are needed in the DWH from the dataframe

In [15]:
df_candidate_dwh = df_candidate[["ID", "InstanceID", "OrganizationGUID", "LanguageGUID", "GenderChoice", "Gender", "Qualification"]]

df_candidate_dwh.head(20)

,ID,InstanceID,OrganizationGUID,LanguageGUID,GenderChoice,Gender,Qualification
0,1,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
1,2,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown
2,2,3,4B79F6DC-F833-4721-82E3-DF6F09AE8EA2,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,None,Gender_Male,Qualification_Unknown
3,2,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
4,3,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown
5,3,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown
6,4,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown
7,5,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor
8,5,3,4B79F6DC-F833-4721-82E3-DF6F09AE8EA2,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,None,Gender_Female,Qualification_Unknown
9,5,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown
10,6,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor
11,7,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown
12,8,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown
13,9,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor
14,9,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
15,10,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor
16,10,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown
17,11,4,B2BABE21-1705-4750-AE99-8D1316755876,BE3C46AE-0192-4A9B-ACEE-37E51836F77C,Gender_Male,Gender_Male,Qualification_Unknown
18,12,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
19,14,2,A9AEA318-F622-4163-A164-5A1B7A6568EC,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Bachelor

Add CandidateKey by combining ID and Instance into 1 code: {ID}{InstanceID}

In [16]:
df_candidate_dwh["CandidateKey"] = df_candidate_dwh["ID"].astype(str) + df_candidate_dwh["InstanceID"].astype(str)
df_candidate_dwh["CandidateKey"].astype(int)

df_candidate_dwh.head(20)

C:\Users\monad\AppData\Local\Temp\ipykernel_22816\1633865774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_candidate_dwh["CandidateKey"] = df_candidate_dwh["ID"].astype(str) + df_candidate_dwh["InstanceID"].astype(str)

,ID,InstanceID,OrganizationGUID,LanguageGUID,GenderChoice,Gender,Qualification,CandidateKey
0,1,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown,14
1,2,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown,22
2,2,3,4B79F6DC-F833-4721-82E3-DF6F09AE8EA2,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,None,Gender_Male,Qualification_Unknown,23
3,2,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown,24
4,3,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown,32
5,3,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown,34
6,4,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown,44
7,5,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor,52
8,5,3,4B79F6DC-F833-4721-82E3-DF6F09AE8EA2,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,None,Gender_Female,Qualification_Unknown,53
9,5,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown,54
10,6,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor,62
11,7,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown,74
12,8,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown,84
13,9,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor,92
14,9,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown,94
15,10,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Bachelor,102
16,10,4,B2BABE21-1705-4750-AE99-8D1316755876,65CAFEA9-CF49-43ED-99AA-83AFE0539978,Gender_Male,Gender_Male,Qualification_Unknown,104
17,11,4,B2BABE21-1705-4750-AE99-8D1316755876,BE3C46AE-0192-4A9B-ACEE-37E51836F77C,Gender_Male,Gender_Male,Qualification_Unknown,114
18,12,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown,124
19,14,2,A9AEA318-F622-4163-A164-5A1B7A6568EC,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Bachelor,142

In [17]:
df_candidate_dwh["CandidateKey"].describe()

count     2292756
unique    2292756
top            14
freq            1
Name: CandidateKey, dtype: object

Make sure columns are in the same order as the ones in the database

In [18]:
df_candidate_dwh = df_candidate_dwh[["CandidateKey", "ID", "InstanceID", "OrganizationGUID", "LanguageGUID", "GenderChoice", "Gender", "Qualification"]]

df_candidate_dwh.head()

,CandidateKey,ID,InstanceID,OrganizationGUID,LanguageGUID,GenderChoice,Gender,Qualification
0,14,1,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
1,22,2,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown
2,23,2,3,4B79F6DC-F833-4721-82E3-DF6F09AE8EA2,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,None,Gender_Male,Qualification_Unknown
3,24,2,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
4,32,3,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown

In [19]:
df_candidate_dwh.rename(columns={'OrganizationGUID': 'Organisation',
                                 'LanguageGUID': 'ChosenLanguage', 
                                 'GenderChoice': 'ChosenGender',}, 
    inplace=True)
df_candidate_dwh.head()

,CandidateKey,ID,InstanceID,Organisation,ChosenLanguage,ChosenGender,Gender,Qualification
0,14,1,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
1,22,2,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown
2,23,2,3,4B79F6DC-F833-4721-82E3-DF6F09AE8EA2,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,None,Gender_Male,Qualification_Unknown
3,24,2,4,B2BABE21-1705-4750-AE99-8D1316755876,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Male,Gender_Male,Qualification_Unknown
4,32,3,2,FDE03D4F-9C9B-4B36-9C0C-F5296C6772F1,FADAABC8-26DD-458B-B07E-BF96B4B3FCED,Gender_Female,Gender_Female,Qualification_Unknown

Write the dataframe to DimCandidate in the DWH

In [20]:
# df_candidate_dwh.to_sql("DimCandidate", channel_dwh, index=False, if_exists="append")

In [21]:
# df_candidate_dwh.to_csv("../csv/DWH structure/DimCandidate.csv", index=False)

In [22]:
for index, row in df_candidate_dwh.iterrows():
    row = list(row)
    query = """INSERT INTO DimCandidate(CandidateKey, ID, InstanceID, Organisation, ChosenLanguage, ChosenGender, Gender, Qualification) VALUES (?,?,?,?,?,?,?,?)"""
    cursor_dwh_lisa.execute(query, row)
channel_dwh_lisa.commit()

total local runtime is about 18m
> creates: 2292756 rows