Imports

In [ ]:
import pandas as pd
import numpy as np
from dep2pyodbc import dep2connection

pd.set_option("display.max_columns", None)

Connection to database

In [3]:
channel_crh = dep2connection("CRH")
channel_dwh_lisa = dep2connection("CRH_DWH")
cursor = channel_dwh_lisa.cursor()

SystemError: <class 'pyodbc.Error'> returned a result with an exception set

Get decoded data from by using the controler script and drop unnecessary columns

In [ ]:
df_decoded = pd.read_csv("../../decoderen/csv/raw_data/fca_investigate.csv")
df_decoded.drop(columns=["Sequence1", "Sequence2", "Sequence3", "InstrumentClassId"], inplace=True)
df_decoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035545 entries, 0 to 3035544
Data columns (total 23 columns):
 #   Column                     Dtype
---  ------                     -----
 0   CandidateId                int64
 1   InstanceId                 int64
 2   ItemId                     int64
 3   TimeSpent                  int64
 4   Answer1                    int64
 5   Answer2                    int64
 6   Answer3                    int64
 7   Competency_1               int64
 8   Correct_answer_comp1_seq1  int64
 9   Correct_answer_comp1_seq2  int64
 10  Correct_answer_comp1_seq3  int64
 11  Competency_2               int64
 12  Correct_answer_comp2_seq1  int64
 13  Correct_answer_comp2_seq2  int64
 14  Correct_answer_comp2_seq3  int64
 15  Competency_3               int64
 16  Correct_answer_comp3_seq1  int64
 17  Correct_answer_comp3_seq2  int64
 18  Correct_answer_comp3_seq3  int64
 19  Competency_4               int64
 20  Correct_answer_comp4_seq1  int64
 21  Correct_answer_comp4_seq2  int64
 22  Correct_answer_comp4_seq3  int64
dtypes: int64(23)
memory usage: 532.7 MB

In [5]:
df_decoded.head()

,CandidateId,InstanceId,ItemId,TimeSpent,Answer1,Answer2,Answer3,Competency_1,Correct_answer_comp1_seq1,Correct_answer_comp1_seq2,Correct_answer_comp1_seq3,Competency_2,Correct_answer_comp2_seq1,Correct_answer_comp2_seq2,Correct_answer_comp2_seq3,Competency_3,Correct_answer_comp3_seq1,Correct_answer_comp3_seq2,Correct_answer_comp3_seq3,Competency_4,Correct_answer_comp4_seq1,Correct_answer_comp4_seq2,Correct_answer_comp4_seq3
0,54,4,222,11,0,0,0,5,3,5,2,0,0,0,0,0,0,0,0,0,0,0,0
1,54,4,223,3,3,4,2,5,1,4,5,3,3,5,2,0,0,0,0,0,0,0,0
2,54,4,226,13,4,3,2,15,5,4,2,3,3,5,2,0,0,0,0,0,0,0,0
3,54,4,229,100,2,0,4,3,2,5,3,0,0,0,0,0,0,0,0,0,0,0,0
4,54,4,238,2,0,0,0,15,3,2,5,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# TODO Delete this cell - only for checking whether the correct answers are the same for the same comp and item

df_check_comp = df_decoded[(df_decoded.ItemId == 201) & (df_decoded.Competency_1 == 11)]
df_check_comp['Correct_answer_comp1_seq1'].unique(), df_check_comp['Correct_answer_comp1_seq2'].unique(), df_check_comp['Correct_answer_comp1_seq3'].unique(),

# Hypothesis true with a really big certainty

(array([2], dtype=int64), array([3], dtype=int64), array([4], dtype=int64))

Get the other data from the FCA tests

In [7]:
df_not_coded = pd.read_sql("SELECT ID, CandidateID, InstanceID, TestStartTime, TestFinishTime, Data, CreatedDate, ModifiedDate, VersionNumber, PostedDate FROM CandidateResultFCA", channel_crh)

df_not_coded.head()

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\2403693097.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_not_coded = pd.read_sql("SELECT ID, CandidateID, InstanceID, TestStartTime, TestFinishTime, Data, CreatedDate, ModifiedDate, VersionNumber, PostedDate FROM CandidateResultFCA", channel_crh)

,ID,CandidateID,InstanceID,TestStartTime,TestFinishTime,Data,CreatedDate,ModifiedDate,VersionNumber,PostedDate
0,1,1222874,1,2012-03-08 10:15:46.363,2012-03-08 11:15:46.363,b'\x00\x0c\x92\x9c\xac\x0bN\x01\x8e\xa0\x00\x0...,2012-03-08 10:15:46.463,2012-03-08 11:06:08.990,v1.0,2019-11-21 06:28:08.150
1,2,1222959,1,2012-03-08 10:16:29.033,2012-03-08 11:16:29.033,b'\x00\x0c\x92\x9b\xa4\x0bN\x01\x8e\xa0\x00\x0...,2012-03-08 10:16:29.157,2012-03-08 10:45:54.760,v1.0,2019-11-21 06:28:08.150
2,3,1222906,1,2012-03-08 10:17:22.647,2012-03-08 11:17:22.647,b'\x00\x0c\x92\x9a\xb0\x0bN\x01\x8e\xa0\x00\x0...,2012-03-08 10:17:22.753,2012-03-08 10:54:10.720,v1.0,2019-11-21 06:28:08.150
3,4,1222857,1,2012-03-08 10:17:56.660,2012-03-08 11:17:56.660,b'\x00\x0c\x92\x99\xac\x0bN\x01\x8e\xa0\x00\x0...,2012-03-08 10:17:56.773,2012-03-08 10:51:31.530,v1.0,2019-11-21 06:28:08.150
4,5,1222909,1,2012-03-08 10:18:05.520,2012-03-08 11:18:05.520,b'\x00\x0c\x92\x9a\xb0\x0bN\x01\x8e\xa0\x00\x0...,2012-03-08 10:18:05.633,2012-03-08 10:58:20.817,v1.0,2019-11-21 06:28:08.150

Combine decoded and other data from FCA in one dataframe

In [8]:
df_fca = pd.merge(df_decoded, df_not_coded, left_on=["CandidateId", "InstanceId"], right_on=["CandidateID", "InstanceID"], how="left")

df_fca.head()

,CandidateId,InstanceId,ItemId,TimeSpent,Answer1,Answer2,Answer3,Competency_1,Correct_answer_comp1_seq1,Correct_answer_comp1_seq2,Correct_answer_comp1_seq3,Competency_2,Correct_answer_comp2_seq1,Correct_answer_comp2_seq2,Correct_answer_comp2_seq3,Competency_3,Correct_answer_comp3_seq1,Correct_answer_comp3_seq2,Correct_answer_comp3_seq3,Competency_4,Correct_answer_comp4_seq1,Correct_answer_comp4_seq2,Correct_answer_comp4_seq3,ID,CandidateID,InstanceID,TestStartTime,TestFinishTime,Data,CreatedDate,ModifiedDate,VersionNumber,PostedDate
0,54,4,222,11,0,0,0,5,3,5,2,0,0,0,0,0,0,0,0,0,0,0,0,133595,54,4,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697
1,54,4,223,3,3,4,2,5,1,4,5,3,3,5,2,0,0,0,0,0,0,0,0,133595,54,4,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697
2,54,4,226,13,4,3,2,15,5,4,2,3,3,5,2,0,0,0,0,0,0,0,0,133595,54,4,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697
3,54,4,229,100,2,0,4,3,2,5,3,0,0,0,0,0,0,0,0,0,0,0,0,133595,54,4,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697
4,54,4,238,2,0,0,0,15,3,2,5,0,0,0,0,0,0,0,0,0,0,0,0,133595,54,4,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697

In [9]:
del df_decoded
del df_not_coded
df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 33 columns):
 #   Column                     Dtype
---  ------                     -----
 0   CandidateId                int64
 1   InstanceId                 int64
 2   ItemId                     int64
 3   TimeSpent                  int64
 4   Answer1                    int64
 5   Answer2                    int64
 6   Answer3                    int64
 7   Competency_1               int64
 8   Correct_answer_comp1_seq1  int64
 9   Correct_answer_comp1_seq2  int64
 10  Correct_answer_comp1_seq3  int64
 11  Competency_2               int64
 12  Correct_answer_comp2_seq1  int64
 13  Correct_answer_comp2_seq2  int64
 14  Correct_answer_comp2_seq3  int64
 15  Competency_3               int64
 16  Correct_answer_comp3_seq1  int64
 17  Correct_answer_comp3_seq2  int64
 18  Correct_answer_comp3_seq3  int64
 19  Competency_4               int64
 20  Correct_answer_comp4_seq1  int64
 21  Correct_answer_comp4_seq2  int64
 22  Correct_answer_comp4_seq3  int64
 23  ID                         int64
 24  CandidateID                int64
 25  InstanceID                 int64
 26  TestStartTime              datetime64[ns]
 27  TestFinishTime             datetime64[ns]
 28  Data                       object
 29  CreatedDate                datetime64[ns]
 30  ModifiedDate               datetime64[ns]
 31  VersionNumber              object
 32  PostedDate                 datetime64[ns]
dtypes: datetime64[ns](5), int64(26), object(2)
memory usage: 764.3+ MB

In [10]:
df_fca[df_fca["CreatedDate"].isnull()]

Empty DataFrame
Columns: [CandidateId, InstanceId, ItemId, TimeSpent, Answer1, Answer2, Answer3, Competency_1, Correct_answer_comp1_seq1, Correct_answer_comp1_seq2, Correct_answer_comp1_seq3, Competency_2, Correct_answer_comp2_seq1, Correct_answer_comp2_seq2, Correct_answer_comp2_seq3, Competency_3, Correct_answer_comp3_seq1, Correct_answer_comp3_seq2, Correct_answer_comp3_seq3, Competency_4, Correct_answer_comp4_seq1, Correct_answer_comp4_seq2, Correct_answer_comp4_seq3, ID, CandidateID, InstanceID, TestStartTime, TestFinishTime, Data, CreatedDate, ModifiedDate, VersionNumber, PostedDate]
Index: []

Get the necesarry data from DimCandidate to use the correct keys in the FCA dataframe and drop columns that are no longer necessary

In [11]:
df_candidate = pd.read_sql("SELECT CandidateKey, ID, InstanceID FROM DimCandidate", channel_dwh_lisa)
df_candidate.head()

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\4256305450.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_candidate = pd.read_sql("SELECT CandidateKey, ID, InstanceID FROM DimCandidate", channel_dwh_lisa)

   CandidateKey  ID  InstanceID
0            14   1           4
1            22   2           2
2            23   2           3
3            24   2           4
4            32   3           2

In [12]:
df_fca = pd.merge(df_fca, df_candidate, left_on=["CandidateId", "InstanceId"], right_on=["ID", "InstanceID"], how="left")
df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 36 columns):
 #   Column                     Dtype
---  ------                     -----
 0   CandidateId                int64
 1   InstanceId                 int64
 2   ItemId                     int64
 3   TimeSpent                  int64
 4   Answer1                    int64
 5   Answer2                    int64
 6   Answer3                    int64
 7   Competency_1               int64
 8   Correct_answer_comp1_seq1  int64
 9   Correct_answer_comp1_seq2  int64
 10  Correct_answer_comp1_seq3  int64
 11  Competency_2               int64
 12  Correct_answer_comp2_seq1  int64
 13  Correct_answer_comp2_seq2  int64
 14  Correct_answer_comp2_seq3  int64
 15  Competency_3               int64
 16  Correct_answer_comp3_seq1  int64
 17  Correct_answer_comp3_seq2  int64
 18  Correct_answer_comp3_seq3  int64
 19  Competency_4               int64
 20  Correct_answer_comp4_seq1  int64
 21  Correct_answer_comp4_seq2  int64
 22  Correct_answer_comp4_seq3  int64
 23  ID_x                       int64
 24  CandidateID                int64
 25  InstanceID_x               int64
 26  TestStartTime              datetime64[ns]
 27  TestFinishTime             datetime64[ns]
 28  Data                       object
 29  CreatedDate                datetime64[ns]
 30  ModifiedDate               datetime64[ns]
 31  VersionNumber              object
 32  PostedDate                 datetime64[ns]
 33  CandidateKey               int64
 34  ID_y                       int64
 35  InstanceID_y               int64
dtypes: datetime64[ns](5), int64(29), object(2)
memory usage: 833.8+ MB

In [13]:
df_fca[["InstanceId", "InstanceID_x", "InstanceID_y"]].head()

   InstanceId  InstanceID_x  InstanceID_y
0           4             4             4
1           4             4             4
2           4             4             4
3           4             4             4
4           4             4             4

In [14]:
df_fca.drop(columns=["CandidateId", "ID_y", "CandidateID", "InstanceId", "InstanceID_x", "InstanceID_y"], inplace=True)
df_fca.rename(columns={"ID_x": "TestID"}, inplace=True)
df_fca.head()

,ItemId,TimeSpent,Answer1,Answer2,Answer3,Competency_1,Correct_answer_comp1_seq1,Correct_answer_comp1_seq2,Correct_answer_comp1_seq3,Competency_2,Correct_answer_comp2_seq1,Correct_answer_comp2_seq2,Correct_answer_comp2_seq3,Competency_3,Correct_answer_comp3_seq1,Correct_answer_comp3_seq2,Correct_answer_comp3_seq3,Competency_4,Correct_answer_comp4_seq1,Correct_answer_comp4_seq2,Correct_answer_comp4_seq3,TestID,TestStartTime,TestFinishTime,Data,CreatedDate,ModifiedDate,VersionNumber,PostedDate,CandidateKey
0,222,11,0,0,0,5,3,5,2,0,0,0,0,0,0,0,0,0,0,0,0,133595,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697,544
1,223,3,3,4,2,5,1,4,5,3,3,5,2,0,0,0,0,0,0,0,0,133595,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697,544
2,226,13,4,3,2,15,5,4,2,3,3,5,2,0,0,0,0,0,0,0,0,133595,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697,544
3,229,100,2,0,4,3,2,5,3,0,0,0,0,0,0,0,0,0,0,0,0,133595,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697,544
4,238,2,0,0,0,15,3,2,5,0,0,0,0,0,0,0,0,0,0,0,0,133595,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,2022-09-08 09:31:54.423,2022-09-08 09:32:11.780,V1.0,2022-09-08 09:32:11.697,544

In [15]:
del df_candidate
df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  TestStartTime              datetime64[ns]
 23  TestFinishTime             datetime64[ns]
 24  Data                       object
 25  CreatedDate                datetime64[ns]
 26  ModifiedDate               datetime64[ns]
 27  VersionNumber              object
 28  PostedDate                 datetime64[ns]
 29  CandidateKey               int64
dtypes: datetime64[ns](5), int64(23), object(2)
memory usage: 694.8+ MB

Get the necesarry data from DimDate to use the correct keys in the FCA dataframe and drop columns that are no longer necessary

In [16]:
df_dates = pd.read_sql("SELECT DateKey, Date FROM DimDate", channel_dwh_lisa)
# df_dates['Date'] = pd.to_datetime(df_dates["Date"], format="%Y-%m-%d")

df_dates

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\205172393.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dates = pd.read_sql("SELECT DateKey, Date FROM DimDate", channel_dwh_lisa)

       DateKey        Date
0     20110101  2011-01-01
1     20110102  2011-01-02
2     20110103  2011-01-03
3     20110104  2011-01-04
4     20110105  2011-01-05
...        ...         ...
5109  20241227  2024-12-27
5110  20241228  2024-12-28
5111  20241229  2024-12-29
5112  20241230  2024-12-30
5113  20241231  2024-12-31

[5114 rows x 2 columns]

* CreatedDate

In [17]:
df_fca["CreatedDate"] = pd.to_datetime(df_fca["CreatedDate"]).dt.date

df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  TestStartTime              datetime64[ns]
 23  TestFinishTime             datetime64[ns]
 24  Data                       object
 25  CreatedDate                object
 26  ModifiedDate               datetime64[ns]
 27  VersionNumber              object
 28  PostedDate                 datetime64[ns]
 29  CandidateKey               int64
dtypes: datetime64[ns](4), int64(23), object(3)
memory usage: 694.8+ MB

In [18]:
df_fca[df_fca["CreatedDate"].isnull()].head()

Empty DataFrame
Columns: [ItemId, TimeSpent, Answer1, Answer2, Answer3, Competency_1, Correct_answer_comp1_seq1, Correct_answer_comp1_seq2, Correct_answer_comp1_seq3, Competency_2, Correct_answer_comp2_seq1, Correct_answer_comp2_seq2, Correct_answer_comp2_seq3, Competency_3, Correct_answer_comp3_seq1, Correct_answer_comp3_seq2, Correct_answer_comp3_seq3, Competency_4, Correct_answer_comp4_seq1, Correct_answer_comp4_seq2, Correct_answer_comp4_seq3, TestID, TestStartTime, TestFinishTime, Data, CreatedDate, ModifiedDate, VersionNumber, PostedDate, CandidateKey]
Index: []

In [19]:
df_fca = pd.merge(df_fca, df_dates, left_on="CreatedDate", right_on="Date", how="left")
df_fca.drop(columns=["Date", "CreatedDate"], inplace=True)
df_fca.rename(columns={"DateKey": "CreatedDateKey"}, inplace=True)

In [20]:
df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  TestStartTime              datetime64[ns]
 23  TestFinishTime             datetime64[ns]
 24  Data                       object
 25  ModifiedDate               datetime64[ns]
 26  VersionNumber              object
 27  PostedDate                 datetime64[ns]
 28  CandidateKey               int64
 29  CreatedDateKey             int64
dtypes: datetime64[ns](4), int64(24), object(2)
memory usage: 694.8+ MB

* ModifiedDate

In [21]:
df_fca["ModifiedDate"] = pd.to_datetime(df_fca["ModifiedDate"]).dt.date

df_fca = pd.merge(df_fca, df_dates, left_on="ModifiedDate", right_on="Date", how="left")
df_fca.drop(columns=["Date", "ModifiedDate"], inplace=True)
df_fca.rename(columns={"DateKey": "ModifiedDateKey"}, inplace=True)

df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  TestStartTime              datetime64[ns]
 23  TestFinishTime             datetime64[ns]
 24  Data                       object
 25  VersionNumber              object
 26  PostedDate                 datetime64[ns]
 27  CandidateKey               int64
 28  CreatedDateKey             int64
 29  ModifiedDateKey            int64
dtypes: datetime64[ns](3), int64(25), object(2)
memory usage: 694.8+ MB

* PostedDate

In [22]:
df_fca["PostedDate"] = pd.to_datetime(df_fca["PostedDate"]).dt.date

df_fca = pd.merge(df_fca, df_dates, left_on="PostedDate", right_on="Date", how="left")
df_fca.drop(columns=["Date", "PostedDate"], inplace=True)
df_fca.rename(columns={"DateKey": "PostedDateKey"}, inplace=True)

df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  TestStartTime              datetime64[ns]
 23  TestFinishTime             datetime64[ns]
 24  Data                       object
 25  VersionNumber              object
 26  CandidateKey               int64
 27  CreatedDateKey             int64
 28  ModifiedDateKey            int64
 29  PostedDateKey              int64
dtypes: datetime64[ns](2), int64(26), object(2)
memory usage: 694.8+ MB

In [23]:
del df_dates

Get the necesarry data from DimTime to use the correct keys in the FCA dataframe and drop columns that are no longer necessary

In [24]:
df_time = pd.read_sql("SELECT TimeKey, tekst FROM DimTime", channel_dwh_lisa)

df_time["tekst"] = pd.to_datetime(df_time["tekst"], format='%H:%M:%S').dt.time

df_time.head()

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\4113371619.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_time = pd.read_sql("SELECT TimeKey, tekst FROM DimTime", channel_dwh_lisa)

   TimeKey     tekst
0        0  00:00:00
1        1  00:00:01
2        2  00:00:02
3        3  00:00:03
4        4  00:00:04

* TestStartTime

In [25]:
df_fca["TestStartTime"] = pd.to_datetime(df_fca["TestStartTime"]).dt.round('s').dt.time

df_fca = pd.merge(df_fca, df_time, left_on="TestStartTime", right_on="tekst", how="left")
df_fca.drop(columns=["tekst", "TestStartTime"], inplace=True)
df_fca.rename(columns={"TimeKey": "TestStartTimeKey"}, inplace=True)

df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  TestFinishTime             datetime64[ns]
 23  Data                       object
 24  VersionNumber              object
 25  CandidateKey               int64
 26  CreatedDateKey             int64
 27  ModifiedDateKey            int64
 28  PostedDateKey              int64
 29  TestStartTimeKey           int64
dtypes: datetime64[ns](1), int64(27), object(2)
memory usage: 694.8+ MB

* TestFinishTime

In [26]:
df_fca["TestFinishTime"] = pd.to_datetime(df_fca["TestFinishTime"]).dt.round('s').dt.time

df_fca = pd.merge(df_fca, df_time, left_on="TestFinishTime", right_on="tekst", how="left")
df_fca.drop(columns=["tekst", "TestFinishTime"], inplace=True)
df_fca.rename(columns={"TimeKey": "TestFinishTimeKey"}, inplace=True)

df_fca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 30 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
 22  Data                       object
 23  VersionNumber              object
 24  CandidateKey               int64
 25  CreatedDateKey             int64
 26  ModifiedDateKey            int64
 27  PostedDateKey              int64
 28  TestStartTimeKey           int64
 29  TestFinishTimeKey          int64
dtypes: int64(28), object(2)
memory usage: 694.8+ MB

In [27]:
del df_time

Split dataftame in a test dataframe, a question dataframe and a competence dataframe

* Test dataframe

In [ ]:
df_test = df_fca[["TestID", "CandidateKey", "CreatedDateKey", "ModifiedDateKey", "PostedDateKey", "TestStartTimeKey", "TestFinishTimeKey", "VersionNumber", "Data"]]

df_test.drop_duplicates(inplace=True)
df_test.reset_index(inplace=True, drop=True)
df_test["TestKey"] = df_test.index + 1
# df_test.rename(columns={"Data" : "HexadecimaleString"}, inplace=True)

df_test.head()

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\988786488.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.drop_duplicates(inplace=True)
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\988786488.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test["FCATestKey"] = df_test.index + 1
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\988786488.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.rename(columns={"Data" : "HexadecimaleString"}, inplace=True)

,TestID,CandidateKey,CreatedDateKey,ModifiedDateKey,PostedDateKey,TestStartTimeKey,TestFinishTimeKey,VersionNumber,HexadecimaleString,FCATestKey
0,133595,544,20220908,20220908,20220908,93154,93212,V1.0,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1
1,133598,854,20221207,20221207,20221207,134516,141829,v1.0,b'\x00\x19r\x9cT\x0cQ\x80\x00\x00\x00\x00\x00\...,2
2,133604,7564,20230809,20230809,20230809,100349,103238,v1.0,b'\x00\x19r\x9a\xb0\nN\x80\x00\x00\x00\x00\x00...,3
3,133645,13914,20231103,20231103,20231103,95141,104332,v1.0,b'\x00\x19r\x9b4\x0cQ\x80\x00\x00\x00\x00\x00\...,4
4,133637,14244,20231025,20231025,20231025,62301,71219,v1.0,b'\x00\x19r\x99t\x0cQ\x80\x00\x00\x00\x00\x00\...,5

In [ ]:
df_test = df_fca[["TestID", "CandidateKey", "CreatedDateKey", "ModifiedDateKey", "PostedDateKey", "TestStartTimeKey", "TestFinishTimeKey", "VersionNumber", "Data"]]

df_test.drop_duplicates(inplace=True)
df_test.reset_index(inplace=True, drop=True)
df_test["TestKey"] = df_test.index + 1
# df_test.rename(columns={"Data" : "HexadecimaleString"}, inplace=True)

df_test.head()

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\988786488.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.drop_duplicates(inplace=True)
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\988786488.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test["FCATestKey"] = df_test.index + 1
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\988786488.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.rename(columns={"Data" : "HexadecimaleString"}, inplace=True)

,TestID,CandidateKey,CreatedDateKey,ModifiedDateKey,PostedDateKey,TestStartTimeKey,TestFinishTimeKey,VersionNumber,HexadecimaleString,FCATestKey
0,133595,544,20220908,20220908,20220908,93154,93212,V1.0,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...,1
1,133598,854,20221207,20221207,20221207,134516,141829,v1.0,b'\x00\x19r\x9cT\x0cQ\x80\x00\x00\x00\x00\x00\...,2
2,133604,7564,20230809,20230809,20230809,100349,103238,v1.0,b'\x00\x19r\x9a\xb0\nN\x80\x00\x00\x00\x00\x00...,3
3,133645,13914,20231103,20231103,20231103,95141,104332,v1.0,b'\x00\x19r\x9b4\x0cQ\x80\x00\x00\x00\x00\x00\...,4
4,133637,14244,20231025,20231025,20231025,62301,71219,v1.0,b'\x00\x19r\x99t\x0cQ\x80\x00\x00\x00\x00\x00\...,5

In [ ]:
df_test = df_test[["TestKey", "TestID", "CandidateKey", "CreatedDateKey", "ModifiedDateKey", "PostedDateKey", "TestStartTimeKey", "TestFinishTimeKey", "VersionNumber"]]
df_test.head()

,FCATestKey,TestID,CandidateKey,CreatedDateKey,ModifiedDateKey,PostedDateKey,TestStartTimeKey,TestFinishTimeKey,VersionNumber,HexadecimaleString
0,1,133595,544,20220908,20220908,20220908,93154,93212,V1.0,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
1,2,133598,854,20221207,20221207,20221207,134516,141829,v1.0,b'\x00\x19r\x9cT\x0cQ\x80\x00\x00\x00\x00\x00\...
2,3,133604,7564,20230809,20230809,20230809,100349,103238,v1.0,b'\x00\x19r\x9a\xb0\nN\x80\x00\x00\x00\x00\x00...
3,4,133645,13914,20231103,20231103,20231103,95141,104332,v1.0,b'\x00\x19r\x9b4\x0cQ\x80\x00\x00\x00\x00\x00\...
4,5,133637,14244,20231025,20231025,20231025,62301,71219,v1.0,b'\x00\x19r\x99t\x0cQ\x80\x00\x00\x00\x00\x00\...

* Competence dataframe

In [30]:
df_competence1 = df_fca[["Competency_1", "ItemId", "Correct_answer_comp1_seq1", "Correct_answer_comp1_seq2", "Correct_answer_comp1_seq3"]]
df_competence2 = df_fca[["Competency_2", "ItemId", "Correct_answer_comp2_seq1", "Correct_answer_comp2_seq2", "Correct_answer_comp2_seq3"]]
df_competence3 = df_fca[["Competency_3", "ItemId", "Correct_answer_comp3_seq1", "Correct_answer_comp3_seq2", "Correct_answer_comp3_seq3"]]
df_competence4 = df_fca[["Competency_4", "ItemId", "Correct_answer_comp4_seq1", "Correct_answer_comp4_seq2", "Correct_answer_comp4_seq3"]]
df_competence1.rename(columns={"Competency_1": "CompetenceCode", "Correct_answer_comp1_seq1":"IdealAnswerSequence1", "Correct_answer_comp1_seq2":"IdealAnswerSequence2", "Correct_answer_comp1_seq3":"IdealAnswerSequence3"}, inplace=True)
df_competence2.rename(columns={"Competency_2": "CompetenceCode", "Correct_answer_comp2_seq1":"IdealAnswerSequence1", "Correct_answer_comp2_seq2":"IdealAnswerSequence2", "Correct_answer_comp2_seq3":"IdealAnswerSequence3"}, inplace=True)
df_competence3.rename(columns={"Competency_3": "CompetenceCode", "Correct_answer_comp3_seq1":"IdealAnswerSequence1", "Correct_answer_comp3_seq2":"IdealAnswerSequence2", "Correct_answer_comp3_seq3":"IdealAnswerSequence3"}, inplace=True)
df_competence4.rename(columns={"Competency_4": "CompetenceCode", "Correct_answer_comp4_seq1":"IdealAnswerSequence1", "Correct_answer_comp4_seq2":"IdealAnswerSequence2", "Correct_answer_comp4_seq3":"IdealAnswerSequence3"}, inplace=True)

df_competence = pd.concat([df_competence1, df_competence2, df_competence3, df_competence4])
df_competence.drop_duplicates(inplace=True)
df_competence.reset_index(inplace=True, drop=True)

df_competence.info()

C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\1488032062.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_competence1.rename(columns={"Competency_1": "CompetenceCode", "Correct_answer_comp1_seq1":"IdealAnswerSequence1", "Correct_answer_comp1_seq2":"IdealAnswerSequence2", "Correct_answer_comp1_seq3":"IdealAnswerSequence3"}, inplace=True)
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\1488032062.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_competence2.rename(columns={"Competency_2": "CompetenceCode", "Correct_answer_comp2_seq1":"IdealAnswerSequence1", "Correct_answer_comp2_seq2":"IdealAnswerSequence2", "Correct_answer_comp2_seq3":"IdealAnswerSequence3"}, inplace=True)
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\1488032062.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_competence3.rename(columns={"Competency_3": "CompetenceCode", "Correct_answer_comp3_seq1":"IdealAnswerSequence1", "Correct_answer_comp3_seq2":"IdealAnswerSequence2", "Correct_answer_comp3_seq3":"IdealAnswerSequence3"}, inplace=True)
C:\Users\Mikel\AppData\Local\Temp\ipykernel_6472\1488032062.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_competence4.rename(columns={"Competency_4": "CompetenceCode", "Correct_answer_comp4_seq1":"IdealAnswerSequence1", "Correct_answer_comp4_seq2":"IdealAnswerSequence2", "Correct_answer_comp4_seq3":"IdealAnswerSequence3"}, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 954 entries, 0 to 953
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CompetenceCode        954 non-null    int64
 1   ItemId                954 non-null    int64
 2   IdealAnswerSequence1  954 non-null    int64
 3   IdealAnswerSequence2  954 non-null    int64
 4   IdealAnswerSequence3  954 non-null    int64
dtypes: int64(5)
memory usage: 37.4 KB

In [31]:
df_competence = df_competence[df_competence["CompetenceCode"] != 0]
df_competence["CompetenceKey"] = df_competence.index + 1

df_competence.head()

,CompetenceCode,ItemId,IdealAnswerSequence1,IdealAnswerSequence2,IdealAnswerSequence3,CompetenceKey
0,5,222,3,5,2,1
1,5,223,1,4,5,2
2,15,226,5,4,2,3
3,3,229,2,5,3,4
4,15,238,3,2,5,5

In [32]:
df_competence.tail()

,CompetenceCode,ItemId,IdealAnswerSequence1,IdealAnswerSequence2,IdealAnswerSequence3,CompetenceKey
931,32,363,1,4,2,932
933,36,410,3,2,4,934
934,36,417,1,5,3,935
935,36,423,3,2,5,936
936,31,332,2,4,5,937

* Question dataframe

In [33]:
df_question = df_fca.drop(columns=["CandidateKey", "CreatedDateKey", "ModifiedDateKey", "PostedDateKey", "TestStartTimeKey", "TestFinishTimeKey", "VersionNumber", "Data"])

In [ ]:
df_question = df_fca.drop(columns=["CandidateKey", "CreatedDateKey", "ModifiedDateKey", "PostedDateKey", "TestStartTimeKey", "TestFinishTimeKey", "VersionNumber", "Data"])
df_question.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 22 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ItemId                     int64
 1   TimeSpent                  int64
 2   Answer1                    int64
 3   Answer2                    int64
 4   Answer3                    int64
 5   Competency_1               int64
 6   Correct_answer_comp1_seq1  int64
 7   Correct_answer_comp1_seq2  int64
 8   Correct_answer_comp1_seq3  int64
 9   Competency_2               int64
 10  Correct_answer_comp2_seq1  int64
 11  Correct_answer_comp2_seq2  int64
 12  Correct_answer_comp2_seq3  int64
 13  Competency_3               int64
 14  Correct_answer_comp3_seq1  int64
 15  Correct_answer_comp3_seq2  int64
 16  Correct_answer_comp3_seq3  int64
 17  Competency_4               int64
 18  Correct_answer_comp4_seq1  int64
 19  Correct_answer_comp4_seq2  int64
 20  Correct_answer_comp4_seq3  int64
 21  TestID                     int64
dtypes: int64(22)
memory usage: 509.5 MB

In [35]:
df_question.head()

,ItemId,TimeSpent,Answer1,Answer2,Answer3,Competency_1,Correct_answer_comp1_seq1,Correct_answer_comp1_seq2,Correct_answer_comp1_seq3,Competency_2,Correct_answer_comp2_seq1,Correct_answer_comp2_seq2,Correct_answer_comp2_seq3,Competency_3,Correct_answer_comp3_seq1,Correct_answer_comp3_seq2,Correct_answer_comp3_seq3,Competency_4,Correct_answer_comp4_seq1,Correct_answer_comp4_seq2,Correct_answer_comp4_seq3,TestID
0,222,11,0,0,0,5,3,5,2,0,0,0,0,0,0,0,0,0,0,0,0,133595
1,223,3,3,4,2,5,1,4,5,3,3,5,2,0,0,0,0,0,0,0,0,133595
2,226,13,4,3,2,15,5,4,2,3,3,5,2,0,0,0,0,0,0,0,0,133595
3,229,100,2,0,4,3,2,5,3,0,0,0,0,0,0,0,0,0,0,0,0,133595
4,238,2,0,0,0,15,3,2,5,0,0,0,0,0,0,0,0,0,0,0,0,133595

In [ ]:
df_competence[(df_competence["CompetenceCode"] == 10) & (df_competence["ItemId"] == 422)]

,CompetenceCode,ItemId,IdealAnswerSequence1,IdealAnswerSequence2,IdealAnswerSequence3,CompetenceKey
20,10,422,1,4,5,21
130,10,422,1,2,4,131
180,10,422,1,5,2,181
236,10,422,2,4,3,237
256,10,422,1,2,5,257
332,10,422,3,5,1,333
385,10,422,2,3,4,386
473,10,422,4,2,3,474

In [37]:
for i in [1,2,3,4]:
    df_question = pd.merge(left=df_question, right=df_competence, how='left',
                        left_on=["ItemId", f"Competency_{i}", f"Correct_answer_comp{i}_seq1", f"Correct_answer_comp{i}_seq2", f"Correct_answer_comp{i}_seq3"],
                        right_on=["ItemId", "CompetenceCode", "IdealAnswerSequence1", "IdealAnswerSequence2", "IdealAnswerSequence3"])
    df_question.drop(columns=[f"Competency_{i}", "CompetenceCode", "IdealAnswerSequence1", "IdealAnswerSequence2", "IdealAnswerSequence3"], inplace=True)
    df_question.rename(columns={"CompetenceKey": f"Competence{i}Key"}, inplace=True)

df_question.rename(columns={
    "Answer1" : "AnswerSequence1",
    "Answer2" : "AnswerSequence2",
    "Answer3" : "AnswerSequence3",
})
df_question = df_question.drop(columns=["Correct_answer_comp1_seq1",
                                   "Correct_answer_comp1_seq2",
                                   "Correct_answer_comp1_seq3",
                                   "Correct_answer_comp2_seq1",
                                   "Correct_answer_comp2_seq2",
                                   "Correct_answer_comp2_seq3",
                                   "Correct_answer_comp3_seq1",
                                   "Correct_answer_comp3_seq2",
                                   "Correct_answer_comp3_seq3",
                                   "Correct_answer_comp4_seq1",
                                   "Correct_answer_comp4_seq2",
                                   "Correct_answer_comp4_seq3",])
df_question["FCAQuestionKey"] = df_question.index + 1
df_question.tail()

,ItemId,TimeSpent,Answer1,Answer2,Answer3,TestID,Competence1Key,Competence2Key,Competence3Key,Competence4Key,FCAQuestionKey
3035700,422,80,4,5,2,119246,68,541.0,NaN,NaN,3035701
3035701,423,98,5,3,4,119246,69,NaN,NaN,NaN,3035702
3035702,424,126,1,2,5,119246,70,NaN,NaN,NaN,3035703
3035703,425,443,5,4,1,119246,71,NaN,NaN,NaN,3035704
3035704,426,37,3,5,2,119246,72,NaN,NaN,NaN,3035705

In [38]:
df_question.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   ItemId          int64
 1   TimeSpent       int64
 2   Answer1         int64
 3   Answer2         int64
 4   Answer3         int64
 5   TestID          int64
 6   Competence1Key  int64
 7   Competence2Key  float64
 8   Competence3Key  float64
 9   Competence4Key  float64
 10  FCAQuestionKey  int64
dtypes: float64(3), int64(8)
memory usage: 254.8 MB

In [39]:
df_question = df_question.replace(np.nan, 0)
df_question["Competence2Key"] = df_question["Competence2Key"].astype(int)
df_question["Competence3Key"] = df_question["Competence3Key"].astype(int)
df_question["Competence4Key"] = df_question["Competence4Key"].astype(int)

df_question.head()

,ItemId,TimeSpent,Answer1,Answer2,Answer3,TestID,Competence1Key,Competence2Key,Competence3Key,Competence4Key,FCAQuestionKey
0,222,11,0,0,0,133595,1,0,0,0,1
1,223,3,3,4,2,133595,2,183,0,0,2
2,226,13,4,3,2,133595,3,184,0,0,3
3,229,100,2,0,4,133595,4,0,0,0,4
4,238,2,0,0,0,133595,5,0,0,0,5

In [ ]:
df_question = pd.merge(df_question, df_test[["TestKey", "TestID"]], on="TestID", how="left")

df_question.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   ItemId          int64
 1   TimeSpent       int64
 2   Answer1         int64
 3   Answer2         int64
 4   Answer3         int64
 5   TestID          int64
 6   Competence1Key  int64
 7   Competence2Key  int32
 8   Competence3Key  int32
 9   Competence4Key  int32
 10  FCAQuestionKey  int64
 11  FCATestKey      int64
dtypes: int32(3), int64(9)
memory usage: 243.2 MB

In [41]:
df_test.drop(columns=["TestID"], inplace=True)
df_question.drop(columns=["TestID"], inplace=True)

In [ ]:
df_question = df_question[["FCAQuestionKey", "TestKey", "Competence1Key", "Competence2Key", "Competence3Key", "Competence4Key", "ItemId", "Answer1", "Answer2", "Answer3", "TimeSpent"]]

In [111]:
# df_fca = df_fca[[
#        "TestID",
#        "Data", 
#        "VersionNumber", 
#        "CandidateKey",
#        "CreatedDateKey",
#        "ModifiedDateKey",
#        "PostedDateKey",
#        "TestStartTimeKey",
#        "TestFinishTimeKey"]]

# df_fca.drop_duplicates(inplace=True)
# df_fca.reset_index(inplace=True, drop=True)
# df_fca["FCATestKey"] = df_fca.index + 1
# df_fca.rename(columns={"Data" : "HexadecimaleString"}, inplace=True)

# df_fca

In [112]:
# fca_cols = df_fca.columns.to_list()
# fca_cols.remove("TestID")
# fca_cols.remove("FCATestKey")
# print(fca_cols)
# pd.merge(df_question, df_fca, on=["TestID"], how="inner").drop(columns=fca_cols)

In [113]:
# df_fca.drop(columns=["TestID"], inplace=True)

dataframe for DimTestAnomalies

In [ ]:
df_test_anomalies = pd.read_csv("../../anomalies/FCA/csv/test_anomalies.csv")

df_test_anomalies["AnomaliesKey"] = df_test_anomalies.index + 1

df_test_anomalies.head()

   FCATestKey  SameAnswerPercentage  TimeSpent  TooSlow  TooFast  AnomaliesKey
0           1             31.372549       3001    False    False             1
1           2             31.481481       1706    False     True             2
2           3             29.629630       2160    False     True             3
3           4             33.333333       1964    False     True             4
4           5             25.925926       2356    False    False             5

In [ ]:
df_test = pd.merge(df_test, df_test_anomalies[["TestKey", "AnomaliesKey"]], on="TestKey", how="left")

df_test = df_test[["TestKey", "CandidateKey", "CreatedDateKey", "ModifiedDateKey", "PostedDateKey", "TestStartTimeKey", "TestFinishTimeKey", "AnomaliesKey", "VersionNumber"]]

df_test.head()

,FCATestKey,CandidateKey,CreatedDateKey,ModifiedDateKey,PostedDateKey,TestStartTimeKey,TestFinishTimeKey,AnomaliesKey,VersionNumber,HexadecimaleString
0,1,544,20220908,20220908,20220908,93154,93212,1.0,V1.0,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
1,2,854,20221207,20221207,20221207,134516,141829,2.0,v1.0,b'\x00\x19r\x9cT\x0cQ\x80\x00\x00\x00\x00\x00\...
2,3,7564,20230809,20230809,20230809,100349,103238,3.0,v1.0,b'\x00\x19r\x9a\xb0\nN\x80\x00\x00\x00\x00\x00...
3,4,13914,20231103,20231103,20231103,95141,104332,4.0,v1.0,b'\x00\x19r\x9b4\x0cQ\x80\x00\x00\x00\x00\x00\...
4,5,14244,20231025,20231025,20231025,62301,71219,5.0,v1.0,b'\x00\x19r\x99t\x0cQ\x80\x00\x00\x00\x00\x00\...

In [45]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160067 entries, 0 to 160066
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   FCATestKey          160067 non-null  int64
 1   CandidateKey        160067 non-null  int64
 2   CreatedDateKey      160067 non-null  int64
 3   ModifiedDateKey     160067 non-null  int64
 4   PostedDateKey       160067 non-null  int64
 5   TestStartTimeKey    160067 non-null  int64
 6   TestFinishTimeKey   160067 non-null  int64
 7   AnomaliesKey        1000 non-null    float64
 8   VersionNumber       160067 non-null  object
 9   HexadecimaleString  160067 non-null  object
dtypes: float64(1), int64(7), object(2)
memory usage: 12.2+ MB

In [46]:
df_test_anomalies = df_test_anomalies[["AnomaliesKey", "SameAnswerPercentage", "TooFast", "TooSlow"]]

df_test_anomalies.head()

   AnomaliesKey  SameAnswerPercentage  TooFast  TooSlow
0             1             31.372549    False    False
1             2             31.481481     True    False
2             3             29.629630     True    False
3             4             33.333333     True    False
4             5             25.925926    False    False

dataframe for DimQuestionAnomalies

In [ ]:
df_question_anomalies = pd.read_csv("../../decoded_data/FCA/DimQuestionAnomalies.csv")
df_question_anomalies["AnomaliesKey"] = df_question_anomalies.index + 1

df_question_anomalies.head()

,FCAQuestionKey,ItemId,TimeSpent,TooSlow,TooFast,SameAnswers,AnomaliesKey
0,1,201,411,False,False,False,1
1,2,202,153,False,False,False,2
2,3,203,74,False,False,False,3
3,4,204,186,False,False,False,4
4,5,205,111,False,False,False,5

In [ ]:
df_question = pd.merge(df_question, df_question_anomalies[["FCAQuestionKey", "ItemId", "AnomaliesKey"]], on=["FCAQuestionKey", "ItemId"], how="left")

df_question = df_question[["FCAQuestionKey", "TestKey", "Competence1Key", "Competence2Key", "Competence3Key", "Competence4Key", "AnomaliesKey", "ItemId", "Answer1", "Answer2", "Answer3", "TimeSpent"]]



df_question.head()

,FCAQuestionKey,FCATestKey,Competence1Key,Competence2Key,Competence3Key,Competence4Key,AnomaliesKey,ItemId,Answer1,Answer2,Answer3,TimeSpent
0,1,1,1,0,0,0,NaN,222,0,0,0,11
1,2,1,2,183,0,0,NaN,223,3,4,2,3
2,3,1,3,184,0,0,NaN,226,4,3,2,13
3,4,1,4,0,0,0,NaN,229,2,0,4,100
4,5,1,5,0,0,0,NaN,238,0,0,0,2

In [49]:
df_question.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   FCAQuestionKey  int64
 1   FCATestKey      int64
 2   Competence1Key  int64
 3   Competence2Key  int32
 4   Competence3Key  int32
 5   Competence4Key  int32
 6   AnomaliesKey    float64
 7   ItemId          int64
 8   Answer1         int64
 9   Answer2         int64
 10  Answer3         int64
 11  TimeSpent       int64
dtypes: float64(1), int32(3), int64(8)
memory usage: 243.2 MB

In [50]:
df_question_anomalies = df_question_anomalies[["AnomaliesKey", "SameAnswers", "TooFast", "TooSlow"]]

df_question_anomalies.head()

   AnomaliesKey  SameAnswers  TooFast  TooSlow
0             1        False    False    False
1             2        False    False    False
2             3        False    False    False
3             4        False    False    False
4             5        False    False    False

Result + to database:

* DimTestAnomalies

In [51]:
df_test_anomalies.tail()

     AnomaliesKey  SameAnswerPercentage  TooFast  TooSlow
995           996             24.242424    False     True
996           997             28.787879    False    False
997           998             31.746032    False     True
998           999             22.222222    False     True
999          1000             30.158730    False     True

In [52]:
zeros = {"AnomaliesKey": 0, "SameAnswerPercentage": 0, "TooSlow": 0, "TooFast": 0}
df_test_anomalies = df_test_anomalies._append(zeros, ignore_index=True)

df_test = df_test.replace(np.nan, 0)
df_test["AnomaliesKey"] = df_test["AnomaliesKey"].astype(int)

In [53]:
df_test_anomalies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AnomaliesKey          1001 non-null   int64
 1   SameAnswerPercentage  1001 non-null   float64
 2   TooFast               1001 non-null   int64
 3   TooSlow               1001 non-null   int64
dtypes: float64(1), int64(3)
memory usage: 31.4 KB

In [54]:
for index, row in df_test_anomalies.iterrows():
    row = list(row)
    query = """INSERT INTO DimTestAnomalies(AnomaliesKey, SameAnswer, TooFast, TooSlow) VALUES (?,?,?,?)"""
    cursor.execute(query, row)
channel_dwh_lisa.commit()

* DimQuestionAnomalies

In [55]:
zeros = {"AnomaliesKey": 0, "SameAnswers": 0, "TooSlow": 0, "TooFast": 0}
df_question_anomalies = df_question_anomalies._append(zeros, ignore_index=True)

df_question = df_question.replace(np.nan, 0)
df_question["AnomaliesKey"] = df_question["AnomaliesKey"].astype(int)

In [56]:
df_question_anomalies.tail()

       AnomaliesKey  SameAnswers  TooFast  TooSlow
20037         20038            0        0        0
20038         20039            0        0        0
20039         20040            0        0        0
20040         20041            0        0        0
20041             0            0        0        0

In [57]:
df_question_anomalies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20042 entries, 0 to 20041
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AnomaliesKey  20042 non-null  int64
 1   SameAnswers   20042 non-null  int64
 2   TooFast       20042 non-null  int64
 3   TooSlow       20042 non-null  int64
dtypes: int64(4)
memory usage: 626.4 KB

In [58]:
for index, row in df_question_anomalies.iterrows():
    row = list(row)
    query = """INSERT INTO DimQuestionAnomalies(AnomaliesKey, SameAnswer, TooFast, TooSlow)
            VALUES (?,?,?,?)"""
    cursor.execute(query, row)
channel_dwh_lisa.commit()

* DimCompetence

In [59]:
df_competence = df_competence[["CompetenceKey", "CompetenceCode", "ItemId", "IdealAnswerSequence1", "IdealAnswerSequence2", "IdealAnswerSequence3"]]

# so SQL Server doesn't complain that there is a non existing foreign key
zeros = {"CompetenceKey": 0, "CompetenceCode": 0, "ItemId": 0, "IdealAnswerSequence1": 0, "IdealAnswerSequence2": 0, "IdealAnswerSequence3": 0}
df_competence = df_competence._append(zeros, ignore_index=True)


df_competence.head()

,CompetenceKey,CompetenceCode,ItemId,IdealAnswerSequence1,IdealAnswerSequence2,IdealAnswerSequence3
0,1,5,222,3,5,2
1,2,5,223,1,4,5
2,3,15,226,5,4,2
3,4,3,229,2,5,3
4,5,15,238,3,2,5

In [60]:
df_competence.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CompetenceKey         736 non-null    int64
 1   CompetenceCode        736 non-null    int64
 2   ItemId                736 non-null    int64
 3   IdealAnswerSequence1  736 non-null    int64
 4   IdealAnswerSequence2  736 non-null    int64
 5   IdealAnswerSequence3  736 non-null    int64
dtypes: int64(6)
memory usage: 34.6 KB

In [61]:
for index, row in df_competence.iterrows():
    row = list(row)
    query = """INSERT INTO DimCompetence(CompetenceKey, CompetenceCode, ItemID, IdealAnswerSequence1, IdealAnswerSequence2, IdealAnswerSequence3) VALUES(?,?,?,?,?,?)"""
    cursor.execute(query, row)
channel_dwh_lisa.commit()

In [133]:
# df_competence.to_csv("../csv/DWH structure/DimCompetence.csv", index=False)

* FactTest

In [62]:
df_test.head()

,FCATestKey,CandidateKey,CreatedDateKey,ModifiedDateKey,PostedDateKey,TestStartTimeKey,TestFinishTimeKey,AnomaliesKey,VersionNumber,HexadecimaleString
0,1,544,20220908,20220908,20220908,93154,93212,1,V1.0,b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
1,2,854,20221207,20221207,20221207,134516,141829,2,v1.0,b'\x00\x19r\x9cT\x0cQ\x80\x00\x00\x00\x00\x00\...
2,3,7564,20230809,20230809,20230809,100349,103238,3,v1.0,b'\x00\x19r\x9a\xb0\nN\x80\x00\x00\x00\x00\x00...
3,4,13914,20231103,20231103,20231103,95141,104332,4,v1.0,b'\x00\x19r\x9b4\x0cQ\x80\x00\x00\x00\x00\x00\...
4,5,14244,20231025,20231025,20231025,62301,71219,5,v1.0,b'\x00\x19r\x99t\x0cQ\x80\x00\x00\x00\x00\x00\...

In [63]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160067 entries, 0 to 160066
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   FCATestKey          160067 non-null  int64
 1   CandidateKey        160067 non-null  int64
 2   CreatedDateKey      160067 non-null  int64
 3   ModifiedDateKey     160067 non-null  int64
 4   PostedDateKey       160067 non-null  int64
 5   TestStartTimeKey    160067 non-null  int64
 6   TestFinishTimeKey   160067 non-null  int64
 7   AnomaliesKey        160067 non-null  int32
 8   VersionNumber       160067 non-null  object
 9   HexadecimaleString  160067 non-null  object
dtypes: int32(1), int64(7), object(2)
memory usage: 11.6+ MB

In [ ]:
for index, row in df_test.iterrows():
    row = list(row)
    query = """INSERT INTO FactTest(TestKey, CandidateKey, CreatedDateKey, ModifiedDateKey, PostedDateKey, TestStartTimeKey, TestFinishTimeKey, AnomaliesKey, VersionNumber) 
            VALUES(?,?,?,?,?,?,?,?,?,?)"""
    cursor.execute(query, row)
channel_dwh_lisa.commit()

In [ ]:
# df_test.to_csv("../csv/DWH structure/FactTest.csv", index=False)

* FactQuestionFCA

In [65]:
df_question.head()

,FCAQuestionKey,FCATestKey,Competence1Key,Competence2Key,Competence3Key,Competence4Key,AnomaliesKey,ItemId,Answer1,Answer2,Answer3,TimeSpent
0,1,1,1,0,0,0,0,222,0,0,0,11
1,2,1,2,183,0,0,0,223,3,4,2,3
2,3,1,3,184,0,0,0,226,4,3,2,13
3,4,1,4,0,0,0,0,229,2,0,4,100
4,5,1,5,0,0,0,0,238,0,0,0,2

In [66]:
df_question.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035705 entries, 0 to 3035704
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   FCAQuestionKey  int64
 1   FCATestKey      int64
 2   Competence1Key  int64
 3   Competence2Key  int32
 4   Competence3Key  int32
 5   Competence4Key  int32
 6   AnomaliesKey    int32
 7   ItemId          int64
 8   Answer1         int64
 9   Answer2         int64
 10  Answer3         int64
 11  TimeSpent       int64
dtypes: int32(4), int64(8)
memory usage: 231.6 MB

In [ ]:
for index, row in df_question.iterrows():
    row = list(row)
    query = """
            INSERT INTO FactQuestionFCA(FCAQuestionKey, TestKey, Competence1Key, Competence2Key, Competence3Key, Competence4Key, AnomaliesKey, ItemID, AnswerSequence1, AnswerSequence2, AnswerSequence3, TimeSpent)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
            """
    cursor.execute(query, row)
channel_dwh_lisa.commit()

In [68]:
df_question_anomalies.max(axis=0)["AnomaliesKey"]

20041

> 20041

In [142]:
# df_question.to_csv("../csv/DWH structure/FactQuestionFCA.csv", index=False)