In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
def compare_anomaly_models(*model_dfs, id_column='TestKey'):
    df_combined = pd.DataFrame({id_column: model_dfs[0][0][id_column]})
    
    # Voeg resultaten van elk model toe
    number_of_anomalies = 0
    model_names = []
    for df, model_name in model_dfs:
        number_of_anomalies +=1 
        model_names.append(model_name)
        df_combined = df_combined.merge(
            df[[id_column, 'is_anomaly']],
            on=id_column,
            suffixes=('', f'_{model_name}')
        )
        df_combined = df_combined.rename(columns={'is_anomaly': f'{model_name}_anomaly'})
    
    # Tel het aantal anomaliedetecties per datapunt
    anomaly_columns = [col for col in df_combined.columns if col.endswith('_anomaly')]
    df_combined['anomaly_count'] = df_combined[anomaly_columns].sum(axis=1)

    df_combined['anomaly_score'] = df_combined['anomaly_count'] / number_of_anomalies 
    
    return df_combined

## Test 
### import csv's

In [ ]:
df_copod = pd.read_csv('./csv/copod.csv')
df_ecod = pd.read_csv('./csv/ecod.csv')
df_i_forest = pd.read_csv('./csv/i_forest.csv')
df_lof = pd.read_csv('./csv/lof.csv')
df_abod = pd.read_csv('./csv/abod.csv')
# df_neighbours = pd.read_csv('./csv/neighbours.csv')

### Compare and anomaly score

In [ ]:
df_compare = compare_anomaly_models(
    (df_copod, 'copod'), 
    (df_ecod, 'ecod'), 
    (df_i_forest, 'i_forest'),
    (df_lof, 'lof'),
    (df_abod, 'abod'),
    # (df_neighbours, 'neighbours'),
    id_column='TestKey'
)
df_compare.head()

,TestKey,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
0,166962,0,0,0,0,1,1,0.2
1,166963,0,0,0,0,0,0,0.0
2,166964,0,0,0,0,0,0,0.0
3,166965,1,1,1,1,1,5,1.0
4,166966,0,0,0,0,0,0,0.0

In [15]:
df_compare.to_csv('./csv/compare.csv', index=False)

In [16]:
df_test_anomalies = df_compare
df_test_anomalies

,TestKey,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
0,166962,0,0,0,0,1,1,0.2
1,166963,0,0,0,0,0,0,0.0
2,166964,0,0,0,0,0,0,0.0
3,166965,1,1,1,1,1,5,1.0
4,166966,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...
5581,172543,0,0,0,0,0,0,0.0
5582,172544,0,0,0,0,0,0,0.0
5583,172545,0,0,0,0,0,0,0.0
5584,172546,0,0,0,0,0,0,0.0
5585,172547,0,0,0,0,0,0,0.0

### Store in DimTestAnomalies

In [17]:
df_test_anomalies.set_index("TestKey", inplace=True)
df_test_anomalies.to_csv("../../decoded_data/PAQ/DimTestAnomalies.csv")
df_test_anomalies.head()

,copod_anomaly,ecod_anomaly,i_forest_anomaly,lof_anomaly,abod_anomaly,anomaly_count,anomaly_score
TestKey,,,,,,,
166962,0,0,0,0,1,1,0.2
166963,0,0,0,0,0,0,0.0
166964,0,0,0,0,0,0,0.0
166965,1,1,1,1,1,5,1.0
166966,0,0,0,0,0,0,0.0

## QUESTION 
# import csvs

In [ ]:
# df_question_same_ans = pd.read_csv('./csv/same_answers_question_checked.csv')
# df_question_time_spent = pd.read_csv('./csv/time_spent_question_checked.csv')


# same answer + time spent

In [ ]:
# df_question_anomalies = df_question_time_spent.merge(df_question_same_ans)


# store in DimQuestionAnomalies

In [ ]:
# df_question_anomalies.set_index("QuestionKey", inplace=True)
# df_question_anomalies.to_csv('../../decoded_data/SJT/DimQuestionAnomalies.csv')