# Preprocessing

In [1]:
import pyodbc
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df_test = pd.read_csv('../../../decoded_data/PAQ/FactTest.csv')
df_question = pd.read_csv('../../../decoded_data/PAQ/FactQuestionPAQ.csv')

In [3]:
df_test.drop(columns=['VersionNumber', 'Test'], inplace=True)
df_test.head()

   CandidateKey  CreatedDateKey  TestKey
0      38114181        20190123   166962
1      38046331        20190110   166963
2      38114191        20190128   166964
3      38201141        20190206   166965
4      38337341        20190227   166966

In [4]:
df_question.drop(columns=['InstanceID', 'Test'], inplace=True)
df_question.head()

   QuestionKey LeftStatement RightStatement  AnswerVal  TestKey
0            1         BEW_1          BEH_1          1   166962
1            2         REA_1          OPT_1          5   166962
2            3         REG_1          AFW_1          5   166962
3            4         RUS_1          ENE_1          5   166962
4            5         OVE_1          GED_1          5   166962

In [5]:
df = df_question.merge(df_test, on='TestKey')
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,CreatedDateKey
0,1,BEW_1,BEH_1,1,166962,38114181,20190123
1,2,REA_1,OPT_1,5,166962,38114181,20190123
2,3,REG_1,AFW_1,5,166962,38114181,20190123
3,4,RUS_1,ENE_1,5,166962,38114181,20190123
4,5,OVE_1,GED_1,5,166962,38114181,20190123

### CreatedDate

In [6]:
df["CreatedDateKey"] = pd.to_datetime(df.CreatedDateKey, format="%Y%m%d")
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,CreatedDateKey
0,1,BEW_1,BEH_1,1,166962,38114181,2019-01-23
1,2,REA_1,OPT_1,5,166962,38114181,2019-01-23
2,3,REG_1,AFW_1,5,166962,38114181,2019-01-23
3,4,RUS_1,ENE_1,5,166962,38114181,2019-01-23
4,5,OVE_1,GED_1,5,166962,38114181,2019-01-23

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   CreatedDateKey  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 152.3+ MB

In [8]:
df['Year'] = pd.DatetimeIndex(df['CreatedDateKey']).year
df['Month'] = pd.DatetimeIndex(df['CreatedDateKey']).month
df['Day'] = pd.DatetimeIndex(df['CreatedDateKey']).dayofweek
df.drop(columns=['CreatedDateKey'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

In [9]:
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2

## Cleaning

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

In [11]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

### Make numerical

In [12]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int64
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(3), int64(4), object(2)
memory usage: 163.2+ MB

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2

In [13]:
only_int = df.AnswerVal.apply(lambda x: x % 1 == 0).all()
if only_int:
    print('In the column AnswerVal none of the values have a value that needs to be stored as a float, therefor we can change the datatype to integer.')
    df['AnswerVal'] = df['AnswerVal'].astype(int)
df.info()

In the column AnswerVal none of the values have a value that needs to be stored as a float, therefor we can change the datatype to integer.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2852280 entries, 0 to 2852279
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   QuestionKey     int64
 1   LeftStatement   object
 2   RightStatement  object
 3   AnswerVal       int32
 4   TestKey         int64
 5   CandidateKey    int64
 6   Year            int32
 7   Month           int32
 8   Day             int32
dtypes: int32(4), int64(3), object(2)
memory usage: 152.3+ MB

### Foutieve waarden

In [14]:
is_valid = df['AnswerVal'].isin([1, 2, 3, 4, 5]).all()

if not is_valid: 
    print("Some values in the AnswerVal column do not fall in the permitted range.")
    df = df[df['AnswerVal'].isin([1, 2, 3, 4, 5])]
else: 
    print("All values in the AnswerVal column fall in the permitted range.")

Some values in the AnswerVal column do not fall in the permitted range.

## Preprocessing per question

In [15]:
df.columns

Index(['QuestionKey', 'LeftStatement', 'RightStatement', 'AnswerVal',
       'TestKey', 'CandidateKey', 'Year', 'Month', 'Day'],
      dtype='object')

#### Statement specific

In [16]:
df_statement_specific = df[['QuestionKey', 'LeftStatement', 'RightStatement', 'AnswerVal',
       'TestKey', 'CandidateKey', 'Year', 'Month', 'Day']]
df_statement_specific.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2

In [17]:
df_statement_specific['StatementPair'] = df_statement_specific.LeftStatement + df_statement_specific.RightStatement

In [18]:
df_statement_specific.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day,StatementPair
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2,BEW_1BEH_1
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2,REA_1OPT_1
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2,REG_1AFW_1
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2,RUS_1ENE_1
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2,OVE_1GED_1

In [19]:
le = LabelEncoder()
df_statement_specific['StatementPair'] = le.fit_transform(df_statement_specific['StatementPair'])

In [20]:
df_statement_specific.drop(columns=['LeftStatement', 'RightStatement'], inplace=True)
df_statement_specific.head()

,QuestionKey,AnswerVal,TestKey,CandidateKey,Year,Month,Day,StatementPair
0,1,1,166962,38114181,2019,1,2,15
1,2,5,166962,38114181,2019,1,2,126
2,3,5,166962,38114181,2019,1,2,132
3,4,5,166962,38114181,2019,1,2,138
4,5,5,166962,38114181,2019,1,2,114

#### Statement type specific

In [21]:
df.columns

Index(['QuestionKey', 'LeftStatement', 'RightStatement', 'AnswerVal',
       'TestKey', 'CandidateKey', 'Year', 'Month', 'Day'],
      dtype='object')

In [22]:
df_type = df[['QuestionKey', 'LeftStatement', 'RightStatement', 'AnswerVal',
       'TestKey', 'CandidateKey', 'Year', 'Month', 'Day']]
df_type.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5,166962,38114181,2019,1,2

In [23]:
df_type['LeftStatement_type'] = df_type['LeftStatement'].str.split('_').str[0]
df_type['RightStatement_type'] = df_type['RightStatement'].str.split('_').str[0]
df_type.drop(columns=['RightStatement', 'LeftStatement'], inplace=True)
df_type.head()

,QuestionKey,AnswerVal,TestKey,CandidateKey,Year,Month,Day,LeftStatement_type,RightStatement_type
0,1,1,166962,38114181,2019,1,2,BEW,BEH
1,2,5,166962,38114181,2019,1,2,REA,OPT
2,3,5,166962,38114181,2019,1,2,REG,AFW
3,4,5,166962,38114181,2019,1,2,RUS,ENE
4,5,5,166962,38114181,2019,1,2,OVE,GED

In [24]:
df_type['StatementTypePair'] = df_type.LeftStatement_type + '_' + df_type.RightStatement_type

In [25]:
df_type.head()

,QuestionKey,AnswerVal,TestKey,CandidateKey,Year,Month,Day,LeftStatement_type,RightStatement_type,StatementTypePair
0,1,1,166962,38114181,2019,1,2,BEW,BEH,BEW_BEH
1,2,5,166962,38114181,2019,1,2,REA,OPT,REA_OPT
2,3,5,166962,38114181,2019,1,2,REG,AFW,REG_AFW
3,4,5,166962,38114181,2019,1,2,RUS,ENE,RUS_ENE
4,5,5,166962,38114181,2019,1,2,OVE,GED,OVE_GED

In [26]:
# le = LabelEncoder()
# df_type['StatementTypePair'] = le.fit_transform(df_type['StatementTypePair'])

In [27]:
df_type.drop(columns=['LeftStatement_type', 'RightStatement_type'], inplace=True)
df_type.head()

,QuestionKey,AnswerVal,TestKey,CandidateKey,Year,Month,Day,StatementTypePair
0,1,1,166962,38114181,2019,1,2,BEW_BEH
1,2,5,166962,38114181,2019,1,2,REA_OPT
2,3,5,166962,38114181,2019,1,2,REG_AFW
3,4,5,166962,38114181,2019,1,2,RUS_ENE
4,5,5,166962,38114181,2019,1,2,OVE_GED

In [28]:
len(df_type.StatementTypePair.unique())

81

gek idee

In [29]:
df = df_type[['TestKey', 'QuestionKey', 'StatementTypePair', 'AnswerVal']]
df.head()

   TestKey  QuestionKey StatementTypePair  AnswerVal
0   166962            1           BEW_BEH          1
1   166962            2           REA_OPT          5
2   166962            3           REG_AFW          5
3   166962            4           RUS_ENE          5
4   166962            5           OVE_GED          5

In [30]:
df = df.groupby(['TestKey', 'StatementTypePair'])['AnswerVal'].sum().unstack(fill_value=0)
df.reset_index(inplace=True)
df.head()

StatementTypePair,TestKey,AHA_BHA,AHA_EHA,AHZ_AHA,AHZ_CHA,AHZ_DHA,AHZ_EHA,APZ_DHA,APZ_DZA,AZA_DHA,...,OVE_GED,PLI_ZFS,REA_OPT,REG_AFW,RUS_ENE,SAL_SBE,STA_AMB,VOL_LEI,ZEL_SAM,ZIC_AND
0,166962,0,0,0,0,0,0,0,0,0,...,22,26,26,18,18,25,18,16,14,17
1,166963,0,0,0,0,0,0,0,0,0,...,22,23,17,15,12,22,16,17,14,18
2,166964,0,0,0,0,0,0,0,0,0,...,21,18,23,21,16,16,21,17,18,22
3,166965,0,0,0,0,0,0,0,0,0,...,23,26,28,25,26,25,26,24,25,24
4,166966,0,0,0,0,0,0,0,0,0,...,18,18,16,16,18,20,16,18,17,17

In [31]:
df.to_csv('../csv/preprocessed_type_pairs.csv', index=False)