# Preprocessing

In [1]:
import pyodbc
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df_test = pd.read_csv('../../../decoded_data/PAQ/FactTest.csv')
df_question = pd.read_csv('../../../decoded_data/PAQ/FactQuestionPAQ.csv')

In [3]:
df_test.drop(columns=['VersionNumber', 'Test'], inplace=True)
df_test.head()

   CandidateKey  CreatedDateKey  TestKey
0      38114181        20190123   166962
1      38046331        20190110   166963
2      38114191        20190128   166964
3      38201141        20190206   166965
4      38337341        20190227   166966

In [4]:
df_question.drop(columns=['InstanceID', 'Test'], inplace=True)
df_question.head()

   QuestionKey LeftStatement RightStatement  AnswerVal  TestKey
0            1         BEW_1          BEH_1        1.0   166962
1            2         REA_1          OPT_1        5.0   166962
2            3         REG_1          AFW_1        5.0   166962
3            4         RUS_1          ENE_1        5.0   166962
4            5         OVE_1          GED_1        5.0   166962

In [5]:
df = df_question.merge(df_test, on='TestKey')
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,CreatedDateKey
0,1,BEW_1,BEH_1,1.0,166962,38114181,20190123
1,2,REA_1,OPT_1,5.0,166962,38114181,20190123
2,3,REG_1,AFW_1,5.0,166962,38114181,20190123
3,4,RUS_1,ENE_1,5.0,166962,38114181,20190123
4,5,OVE_1,GED_1,5.0,166962,38114181,20190123

### CreatedDate

In [6]:
df["CreatedDateKey"] = pd.to_datetime(df.CreatedDateKey, format="%Y%m%d")
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,CreatedDateKey
0,1,BEW_1,BEH_1,1.0,166962,38114181,2019-01-23
1,2,REA_1,OPT_1,5.0,166962,38114181,2019-01-23
2,3,REG_1,AFW_1,5.0,166962,38114181,2019-01-23
3,4,RUS_1,ENE_1,5.0,166962,38114181,2019-01-23
4,5,OVE_1,GED_1,5.0,166962,38114181,2019-01-23

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955148 entries, 0 to 955147
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   QuestionKey     955148 non-null  int64
 1   LeftStatement   955148 non-null  object
 2   RightStatement  955148 non-null  object
 3   AnswerVal       955147 non-null  float64
 4   TestKey         955148 non-null  int64
 5   CandidateKey    955148 non-null  int64
 6   CreatedDateKey  955148 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 51.0+ MB

In [8]:
df['Year'] = pd.DatetimeIndex(df['CreatedDateKey']).year
df['Month'] = pd.DatetimeIndex(df['CreatedDateKey']).month
df['Day'] = pd.DatetimeIndex(df['CreatedDateKey']).dayofweek
df.drop(columns=['CreatedDateKey'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955148 entries, 0 to 955147
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   QuestionKey     955148 non-null  int64
 1   LeftStatement   955148 non-null  object
 2   RightStatement  955148 non-null  object
 3   AnswerVal       955147 non-null  float64
 4   TestKey         955148 non-null  int64
 5   CandidateKey    955148 non-null  int64
 6   Year            955148 non-null  int32
 7   Month           955148 non-null  int32
 8   Day             955148 non-null  int32
dtypes: float64(1), int32(3), int64(3), object(2)
memory usage: 54.7+ MB

In [9]:
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1.0,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5.0,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5.0,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5.0,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5.0,166962,38114181,2019,1,2

## Cleaning

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955148 entries, 0 to 955147
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   QuestionKey     955148 non-null  int64
 1   LeftStatement   955148 non-null  object
 2   RightStatement  955148 non-null  object
 3   AnswerVal       955147 non-null  float64
 4   TestKey         955148 non-null  int64
 5   CandidateKey    955148 non-null  int64
 6   Year            955148 non-null  int32
 7   Month           955148 non-null  int32
 8   Day             955148 non-null  int32
dtypes: float64(1), int32(3), int64(3), object(2)
memory usage: 54.7+ MB

In [11]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 955147 entries, 0 to 955146
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   QuestionKey     955147 non-null  int64
 1   LeftStatement   955147 non-null  object
 2   RightStatement  955147 non-null  object
 3   AnswerVal       955147 non-null  float64
 4   TestKey         955147 non-null  int64
 5   CandidateKey    955147 non-null  int64
 6   Year            955147 non-null  int32
 7   Month           955147 non-null  int32
 8   Day             955147 non-null  int32
dtypes: float64(1), int32(3), int64(3), object(2)
memory usage: 61.9+ MB

### Make numerical

In [12]:
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,BEW_1,BEH_1,1.0,166962,38114181,2019,1,2
1,2,REA_1,OPT_1,5.0,166962,38114181,2019,1,2
2,3,REG_1,AFW_1,5.0,166962,38114181,2019,1,2
3,4,RUS_1,ENE_1,5.0,166962,38114181,2019,1,2
4,5,OVE_1,GED_1,5.0,166962,38114181,2019,1,2

In [13]:
le = LabelEncoder()
df['LeftStatement'] = le.fit_transform(df['LeftStatement'])
df['RightStatement'] = le.fit_transform(df['RightStatement'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 955147 entries, 0 to 955146
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   QuestionKey     955147 non-null  int64
 1   LeftStatement   955147 non-null  int32
 2   RightStatement  955147 non-null  int32
 3   AnswerVal       955147 non-null  float64
 4   TestKey         955147 non-null  int64
 5   CandidateKey    955147 non-null  int64
 6   Year            955147 non-null  int32
 7   Month           955147 non-null  int32
 8   Day             955147 non-null  int32
dtypes: float64(1), int32(5), int64(3)
memory usage: 54.7 MB

In [15]:
df.head()

,QuestionKey,LeftStatement,RightStatement,AnswerVal,TestKey,CandidateKey,Year,Month,Day
0,1,0,18,1.0,166962,38114181,2019,1,2
1,2,42,60,5.0,166962,38114181,2019,1,2
2,3,48,0,5.0,166962,38114181,2019,1,2
3,4,54,30,5.0,166962,38114181,2019,1,2
4,5,30,42,5.0,166962,38114181,2019,1,2

In [16]:
only_int = df.AnswerVal.apply(lambda x: x % 1 == 0).all()
only_int

True

In [17]:
if only_int:
    df['AnswerVal'] = df['AnswerVal'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 955147 entries, 0 to 955146
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   QuestionKey     955147 non-null  int64
 1   LeftStatement   955147 non-null  int32
 2   RightStatement  955147 non-null  int32
 3   AnswerVal       955147 non-null  int32
 4   TestKey         955147 non-null  int64
 5   CandidateKey    955147 non-null  int64
 6   Year            955147 non-null  int32
 7   Month           955147 non-null  int32
 8   Day             955147 non-null  int32
dtypes: int32(6), int64(3)
memory usage: 51.0 MB

### Foutieve waarden

In [67]:
is_valid = df['AnswerVal'].isin([1, 2, 3, 4, 5]).all()

if not is_valid: 
    print("Some values in the AnswerVal column do not fall in the permitted range.")
    df = df[df['AnswerVal'].isin([1, 2, 3, 4, 5])]
else: 
    print("All values in the AnswerVal column fall in the permitted range.")

All values in the AnswerVal column fall in the permitted range.

### Export to csv

In [68]:
df.set_index('TestKey', inplace=True)
df.to_csv('../csv/preprocessed_data.csv')
df.reset_index(inplace=True)

In [49]:
df.reset_index(inplace=True)

## Ander idee

In [83]:
df.LeftStatement.unique()

array([ 0, 42, 48, 54, 30, 18, 36, 60, 78, 24, 72, 84, 66,  6, 12,  1, 19,
       73, 55, 79, 43, 37, 85, 31, 25, 49, 61, 67, 26, 32, 80, 56,  7, 86,
       68, 33, 27, 13, 44,  8,  2, 38, 57, 69,  9, 45, 62, 10, 39, 74, 50,
       81, 14,  3, 70, 58, 28, 75, 63, 15, 34, 20, 87, 51, 82,  4, 64, 29,
       16, 88, 46, 35, 83, 76,  5, 52, 77, 11, 40, 21, 59, 41, 17, 22, 65,
       47, 71, 23, 89, 53])

## PYOD specific preprocessing

In [70]:
df.drop_duplicates(inplace=True)

C:\Users\monad\AppData\Local\Temp\ipykernel_26572\3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [71]:
df.columns

Index(['TestKey', 'QuestionKey', 'LeftStatement', 'RightStatement',
       'AnswerVal', 'CandidateKey', 'Year', 'Month', 'Day'],
      dtype='object')

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502560 entries, 0 to 502559
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   TestKey         502560 non-null  int64
 1   QuestionKey     502560 non-null  int64
 2   LeftStatement   502560 non-null  int32
 3   RightStatement  502560 non-null  int32
 4   AnswerVal       502560 non-null  int32
 5   CandidateKey    502560 non-null  int64
 6   Year            502560 non-null  int32
 7   Month           502560 non-null  int32
 8   Day             502560 non-null  int32
dtypes: int32(6), int64(3)
memory usage: 23.0 MB

failed

In [72]:
# Create a multi-index DataFrame
df_transformed = df.set_index(['QuestionKey', 'TestKey', 'CandidateKey'])
df_transformed = df_transformed[['LeftStatement','RightStatement','AnswerVal']]
df_transformed.drop_duplicates(inplace=True)

In [73]:
# Unstack the QuestionKey
df_transformed = df_transformed.unstack(level='QuestionKey')

In [74]:
df_transformed.head()

                     LeftStatement                                            \
QuestionKey                  1     2     3     4     5     6     7     8
TestKey CandidateKey
166962  38114181               0.0  42.0  48.0  54.0  30.0  18.0  36.0  60.0
166963  38046331               NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
166964  38114191               NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
166965  38201141               NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
166966  38337341               NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

                                  ... AnswerVal                                \
QuestionKey          9     10     ...     4517  5497  6378  6873  9127  9585
TestKey CandidateKey              ...
166962  38114181      78.0  24.0  ...       NaN   NaN   NaN   NaN   NaN   NaN
166963  38046331       NaN   NaN  ...       NaN   NaN   NaN   NaN   NaN   NaN
166964  38114191       NaN   NaN  ...       NaN   NaN   NaN   NaN   NaN   NaN
166965  38201141       NaN   NaN  ...       NaN   NaN   NaN   NaN   NaN   NaN
166966  38337341       NaN   NaN  ...       NaN   NaN   NaN   NaN   NaN   NaN


QuestionKey          10863 29125 49965 80725
TestKey CandidateKey
166962  38114181       NaN   NaN   NaN   NaN
166963  38046331       NaN   NaN   NaN   NaN
166964  38114191       NaN   NaN   NaN   NaN
166965  38201141       NaN   NaN   NaN   NaN
166966  38337341       NaN   NaN   NaN   NaN

[5 rows x 1350 columns]

In [75]:
# Flatten the column multi-index
df_transformed.columns = [f'{col[0]}_{col[1]}' for col in df_transformed.columns]

In [76]:
df_transformed = df_transformed.reset_index()

In [57]:
df_transformed.head()

,TestKey,CandidateKey,LeftStatement_1,LeftStatement_2,LeftStatement_3,LeftStatement_4,LeftStatement_5,LeftStatement_6,LeftStatement_7,LeftStatement_8,...,AnswerVal_4517,AnswerVal_5497,AnswerVal_6378,AnswerVal_6873,AnswerVal_9127,AnswerVal_9585,AnswerVal_10863,AnswerVal_29125,AnswerVal_49965,AnswerVal_80725
0,166962,38114181,0.0,42.0,48.0,54.0,30.0,18.0,36.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,166963,38046331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,166964,38114191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,166965,38201141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,166966,38337341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Columns: 1355 entries, TestKey to AnswerVal_80725
dtypes: float64(1353), int64(2)
memory usage: 307.1 KB